export const FMCG_CATEGORIES = [
  "Agricultural Inputs", "Air Care & Fresheners", "Alcoholic Beverages", "Animal Feed",
  "Baby Care & Hygiene", "Baby Food & Nutrition", "Bath & Body", "Biscuits & Cookies",
  "Canned & Preserved Foods", "Carbonated Soft Drinks", "Cereals & Breakfast Foods",
  "Condiments & Sauces", "Confectionery & Sweets", "Dairy & Chilled Foods",
  "Dairy Beverages", "Dish Care", "Edible Oils", "Feminine Hygiene",
  "Flour & Grains", "Fragrances & Deodorants", "Haircare",
  "Insect Control & Repellents", "Juices & Nectars", "Laundry & Fabric Care",
  "Malt & Energy Drinks", "Men's Grooming", "Noodles & Pasta", "Oral Care",
  "Rice & Cereals", "Seasonings & Spices", "Skincare", "Snacks & Crisps",
  "Spreads & Margarines", "Starch & Derivatives", "Sugar & Sweeteners",
  "Surface & Floor Cleaners", "Tea & Coffee", "Tomato Products",
  "Vitamins & Wellness", "Water & Hydration",
];

export const FMCG_DIVISIONS = {
  "Agricultural Inputs":       "Agro & Industrial",
  "Air Care & Fresheners":     "Home Care",
  "Alcoholic Beverages":       "Beverages",
  "Animal Feed":               "Agro & Industrial",
  "Baby Care & Hygiene":       "Personal Care",
  "Baby Food & Nutrition":     "Foods",
  "Bath & Body":               "Personal Care",
  "Biscuits & Cookies":        "Foods",
  "Canned & Preserved Foods":  "Foods",
  "Carbonated Soft Drinks":    "Beverages",
  "Cereals & Breakfast Foods": "Foods",
  "Condiments & Sauces":       "Foods",
  "Confectionery & Sweets":    "Foods",
  "Dairy & Chilled Foods":     "Foods",
  "Dairy Beverages":           "Beverages",
  "Dish Care":                 "Home Care",
  "Edible Oils":               "Foods",
  "Feminine Hygiene":          "Personal Care",
  "Flour & Grains":            "Foods",
  "Fragrances & Deodorants":   "Personal Care",
  "Haircare":                  "Personal Care",
  "Insect Control & Repellents": "Home Care",
  "Juices & Nectars":          "Beverages",
  "Laundry & Fabric Care":     "Home Care",
  "Malt & Energy Drinks":      "Beverages",
  "Men's Grooming":            "Personal Care",
  "Noodles & Pasta":           "Foods",
  "Oral Care":                 "Personal Care",
  "Rice & Cereals":            "Foods",
  "Seasonings & Spices":       "Foods",
  "Skincare":                  "Personal Care",
  "Snacks & Crisps":           "Foods",
  "Spreads & Margarines":      "Foods",
  "Starch & Derivatives":      "Foods",
  "Sugar & Sweeteners":        "Foods",
  "Surface & Floor Cleaners":  "Home Care",
  "Tea & Coffee":              "Beverages",
  "Tomato Products":           "Foods",
  "Vitamins & Wellness":       "Personal Care",
  "Water & Hydration":         "Beverages",
};
