export const MANUFACTURING_CATEGORIES = [
  "Animal Feed Production", "Baby Care Products", "Beverage Production",
  "Biscuits & Bakery Production", "Cement & Concrete Products",
  "Condiments & Sauce Production", "Consumer Electronics Assembly",
  "Dairy & Chilled Processing", "Detergents & Cleaning Products",
  "Edible Oil Refining", "Energy Storage & Batteries", "Fabrics & Yarns",
  "Feminine Care Products", "Flexible Packaging", "Flavours Colours & Additives",
  "Garments & Finished Apparel", "General Raw Material Inputs",
  "Glass & Glazing Products", "Industrial Lubricants & Chemicals",
  "Industrial Packaging", "Labels & Printed Materials",
  "Meat & Poultry Processing", "Milling & Grain Processing",
  "Noodles & Pasta Production", "Paints & Protective Coatings",
  "Personal Care & Cosmetics", "Pipes & Fittings", "Plumbing & Sanitary",
  "Power Generation & Backup", "Preservatives & Food Chemicals",
  "Primary Packaging", "Roofing & Insulation Materials",
  "Secondary Packaging", "Snacks & Confectionery Production",
  "Solar & Renewable Energy", "Starch & Derivatives Production",
  "Steel & Structural Products", "Sugar & Sweetener Processing",
  "Switchgear & Control Panels", "Technical Textiles",
  "Tiles & Flooring Materials", "Tomato & Vegetable Processing",
  "Wiring & Cable Products",
];

export const MANUFACTURING_DIVISIONS = {
  "Animal Feed Production":           "Food & Beverage Manufacturing",
  "Baby Care Products":               "Home & Personal Care Manufacturing",
  "Beverage Production":              "Food & Beverage Manufacturing",
  "Biscuits & Bakery Production":     "Food & Beverage Manufacturing",
  "Cement & Concrete Products":       "Construction & Building Materials",
  "Condiments & Sauce Production":    "Food & Beverage Manufacturing",
  "Consumer Electronics Assembly":    "Electrical & Electronics Manufacturing",
  "Dairy & Chilled Processing":       "Food & Beverage Manufacturing",
  "Detergents & Cleaning Products":   "Home & Personal Care Manufacturing",
  "Edible Oil Refining":              "Food & Beverage Manufacturing",
  "Energy Storage & Batteries":       "Energy & Power Products",
  "Fabrics & Yarns":                  "Textile & Apparel Manufacturing",
  "Feminine Care Products":           "Home & Personal Care Manufacturing",
  "Flexible Packaging":               "Packaging & Materials",
  "Flavours Colours & Additives":     "Industrial & Chemical Inputs",
  "Garments & Finished Apparel":      "Textile & Apparel Manufacturing",
  "General Raw Material Inputs":      "Industrial & Chemical Inputs",
  "Glass & Glazing Products":         "Construction & Building Materials",
  "Industrial Lubricants & Chemicals":"Industrial & Chemical Inputs",
  "Industrial Packaging":             "Packaging & Materials",
  "Labels & Printed Materials":       "Packaging & Materials",
  "Meat & Poultry Processing":        "Food & Beverage Manufacturing",
  "Milling & Grain Processing":       "Food & Beverage Manufacturing",
  "Noodles & Pasta Production":       "Food & Beverage Manufacturing",
  "Paints & Protective Coatings":     "Construction & Building Materials",
  "Personal Care & Cosmetics":        "Home & Personal Care Manufacturing",
  "Pipes & Fittings":                 "Construction & Building Materials",
  "Plumbing & Sanitary":              "Construction & Building Materials",
  "Power Generation & Backup":        "Energy & Power Products",
  "Preservatives & Food Chemicals":   "Industrial & Chemical Inputs",
  "Primary Packaging":                "Packaging & Materials",
  "Roofing & Insulation Materials":   "Construction & Building Materials",
  "Secondary Packaging":              "Packaging & Materials",
  "Snacks & Confectionery Production":"Food & Beverage Manufacturing",
  "Solar & Renewable Energy":         "Energy & Power Products",
  "Starch & Derivatives Production":  "Food & Beverage Manufacturing",
  "Steel & Structural Products":      "Construction & Building Materials",
  "Sugar & Sweetener Processing":     "Food & Beverage Manufacturing",
  "Switchgear & Control Panels":      "Electrical & Electronics Manufacturing",
  "Technical Textiles":               "Textile & Apparel Manufacturing",
  "Tiles & Flooring Materials":       "Construction & Building Materials",
  "Tomato & Vegetable Processing":    "Food & Beverage Manufacturing",
  "Wiring & Cable Products":          "Electrical & Electronics Manufacturing",
};
