export const RETAIL_CATEGORIES = [
  "Arts & Crafts", "Arts & Crafts Materials", "Audio & Visual",
  "Baby Care & Hygiene", "Baby Clothing & Accessories", "Baby Equipment & Gear",
  "Baby Food & Nutrition", "Bags & Accessories", "Bath & Body", "Bedding & Linen",
  "Bedroom Furniture", "Beef & Veal", "Beers & Ciders", "Bicycles & Ride-ons",
  "Biscuits & Cookies", "Books & Media", "Bread & Rolls", "Cakes & Pastries",
  "Cameras & Accessories", "Canned & Preserved Foods", "Candles & Home Fragrance",
  "Cereals & Breakfast Foods", "Checkout & Impulse Items", "Children's Clothing",
  "Cigarettes", "Cigars & Pipe Tobacco", "Computing & Laptops",
  "Condiments & Sauces", "Confectionery Bakery", "Confectionery & Sweets",
  "Cookware & Kitchen Accessories", "Dairy & Chilled", "Edible Oils",
  "Electrical Supplies", "Feminine Care", "Flooring & Tiles", "Flour & Grains",
  "Footwear", "Fragrances & Deodorants", "Fresh Fruits", "Fresh Herbs & Spices",
  "Fresh Juices & Smoothies", "Fresh Vegetables", "Frozen Convenience Foods",
  "Frozen Meat & Poultry", "Frozen Seafood", "Gaming & Consoles",
  "Gift Sets & Hampers", "Greeting Cards & Wrap", "Haircare",
  "Hardware & Fittings", "Homeware & Decor", "Household Cleaning Aids",
  "Juices & Nectars", "Large Appliances", "Laundry & Fabric Care",
  "Lighting & Electrical", "Living Room Furniture", "Malt & Energy Drinks",
  "Men's Clothing", "Men's Grooming", "Mobiles & Smartphones",
  "Non-Alcoholic Beverages", "Noodles & Pasta", "Office Furniture",
  "Office Supplies", "Oral Care", "OTC Pharmaceuticals", "Outdoor & Fitness Gear",
  "Outdoor Furniture", "Packaging Accessories", "Paints & Coatings",
  "Pet Care & Accessories", "Pet Food", "Plumbing & Sanitary", "Pork & Lamb",
  "Poultry", "Processed & Deli Meats", "Reusable Bags & Carriers",
  "Rice & Cereals", "Roofing & Insulation", "Savouries & Pies",
  "School Supplies", "Seafood & Fish", "Seasonal & Festive Items",
  "Seasonings & Spices", "Skincare", "Small Appliances", "Smokeless Tobacco",
  "Snacks & Crisps", "Spirits", "Sports Equipment", "Spreads & Margarines",
  "Staples & Pulses", "Storage & Organisation", "Sugar & Sweeteners",
  "Tablets & E-Readers", "Tea & Coffee", "Tech Accessories", "Tomato Products",
  "Toys & Games", "Vitamins & Supplements", "Water & Hydration", "Wine",
  "Women's Clothing",
];

export const RETAIL_DIVISIONS = {
  "Arts & Crafts": "Lifestyle", "Arts & Crafts Materials": "Stationeries",
  "Audio & Visual": "Electronics", "Baby Care & Hygiene": "Baby & Child",
  "Baby Clothing & Accessories": "Baby & Child", "Baby Equipment & Gear": "Baby & Child",
  "Baby Food & Nutrition": "Baby & Child", "Bags & Accessories": "Apparels",
  "Bath & Body": "Health & Beauty", "Bedding & Linen": "Home",
  "Bedroom Furniture": "Furniture", "Beef & Veal": "Butchery",
  "Beers & Ciders": "Groceries", "Bicycles & Ride-ons": "Toys & Sports",
  "Biscuits & Cookies": "Groceries", "Books & Media": "Lifestyle",
  "Bread & Rolls": "Bakery", "Cakes & Pastries": "Bakery",
  "Cameras & Accessories": "Technology", "Canned & Preserved Foods": "Groceries",
  "Candles & Home Fragrance": "Home", "Cereals & Breakfast Foods": "Groceries",
  "Checkout & Impulse Items": "Accessories", "Children's Clothing": "Apparels",
  "Cigarettes": "Tobacco & Cigar", "Cigars & Pipe Tobacco": "Tobacco & Cigar",
  "Computing & Laptops": "Technology", "Condiments & Sauces": "Groceries",
  "Confectionery Bakery": "Bakery", "Confectionery & Sweets": "Groceries",
  "Cookware & Kitchen Accessories": "Home", "Dairy & Chilled": "Groceries",
  "Edible Oils": "Groceries", "Electrical Supplies": "Building Materials",
  "Feminine Care": "Health & Beauty", "Flooring & Tiles": "Building Materials",
  "Flour & Grains": "Groceries", "Footwear": "Apparels",
  "Fragrances & Deodorants": "Health & Beauty", "Fresh Fruits": "Fresh Products",
  "Fresh Herbs & Spices": "Fresh Products", "Fresh Juices & Smoothies": "Fresh Products",
  "Fresh Vegetables": "Fresh Products", "Frozen Convenience Foods": "Frozen Foods",
  "Frozen Meat & Poultry": "Frozen Foods", "Frozen Seafood": "Frozen Foods",
  "Gaming & Consoles": "Technology", "Gift Sets & Hampers": "Gifts",
  "Greeting Cards & Wrap": "Gifts", "Haircare": "Health & Beauty",
  "Hardware & Fittings": "Building Materials", "Homeware & Decor": "Lifestyle",
  "Household Cleaning Aids": "Home", "Juices & Nectars": "Groceries",
  "Large Appliances": "Electronics", "Laundry & Fabric Care": "Home",
  "Lighting & Electrical": "Electronics", "Living Room Furniture": "Furniture",
  "Malt & Energy Drinks": "Groceries", "Men's Clothing": "Apparels",
  "Men's Grooming": "Health & Beauty", "Mobiles & Smartphones": "Technology",
  "Non-Alcoholic Beverages": "Groceries", "Noodles & Pasta": "Groceries",
  "Office Furniture": "Furniture", "Office Supplies": "Stationeries",
  "Oral Care": "Health & Beauty", "OTC Pharmaceuticals": "Health & Beauty",
  "Outdoor & Fitness Gear": "Toys & Sports", "Outdoor Furniture": "Furniture",
  "Packaging Accessories": "Accessories", "Paints & Coatings": "Building Materials",
  "Pet Care & Accessories": "Pets", "Pet Food": "Pets",
  "Plumbing & Sanitary": "Building Materials", "Pork & Lamb": "Butchery",
  "Poultry": "Butchery", "Processed & Deli Meats": "Butchery",
  "Reusable Bags & Carriers": "Accessories", "Rice & Cereals": "Groceries",
  "Roofing & Insulation": "Building Materials", "Savouries & Pies": "Bakery",
  "School Supplies": "Stationeries", "Seafood & Fish": "Butchery",
  "Seasonal & Festive Items": "Gifts", "Seasonings & Spices": "Groceries",
  "Skincare": "Health & Beauty", "Small Appliances": "Electronics",
  "Smokeless Tobacco": "Tobacco & Cigar", "Snacks & Crisps": "Groceries",
  "Spirits": "Groceries", "Sports Equipment": "Toys & Sports",
  "Spreads & Margarines": "Groceries", "Staples & Pulses": "Groceries",
  "Storage & Organisation": "Home", "Sugar & Sweeteners": "Groceries",
  "Tablets & E-Readers": "Technology", "Tea & Coffee": "Groceries",
  "Tech Accessories": "Technology", "Tomato Products": "Groceries",
  "Toys & Games": "Toys & Sports", "Vitamins & Supplements": "Health & Beauty",
  "Water & Hydration": "Groceries", "Wine": "Groceries",
  "Women's Clothing": "Apparels",
};
