import Head from 'next/head';
import { PublicNav } from '../components/layout/PublicNav';
import { PublicFooter } from '../components/layout/PublicFooter';

const LAST_UPDATED = 'March 2026';

const sections = [
  {
    title: '1. Introduction',
    body: 'These Terms of Service ("Terms") govern your access to and use of MarginCOS ("the Platform"), a commercial intelligence platform operated by Carthena Advisory ("we", "us", or "our"). By creating an account or using the Platform, you agree to be bound by these Terms. If you do not agree, do not use the Platform.',
  },
  {
    title: '2. Service Description',
    body: 'MarginCOS is a margin intelligence platform built for businesses navigating inflationary markets, currently serving FMCG, manufacturing, and retail companies. The Platform analyses commercial data across four pillars — Pricing Intelligence, Cost Pass-Through, Channel Economics, and Trade Execution — to identify margin recovery opportunities. Enterprise clients may also access advanced modules including Portfolio Rationalisation, Forward Scenario Engine, Commercial Spend ROI Analyser, and Partner Performance Scorecard.',
  },
  {
    title: '3. Account Registration and Access',
    body: null,
    list: [
      'You must provide accurate and complete information when creating an account.',
      'You are responsible for maintaining the confidentiality of your login credentials.',
      'You must notify us immediately if you become aware of any unauthorised access to your account.',
      'Each account is for use by the individual and company specified during registration. Accounts may not be shared or transferred without our written consent.',
      'We reserve the right to suspend or terminate accounts that violate these Terms.',
    ],
  },
  {
    title: '4. Acceptable Use',
    body: 'You agree to use the Platform only for its intended purpose: analysing your own commercial portfolio data. You may not:',
    list: [
      'Use the Platform for any unlawful purpose or in violation of any applicable law or regulation',
      'Attempt to access another client\u2019s data or interfere with the Platform\u2019s security measures',
      'Reverse-engineer, decompile, or attempt to extract the source code of the Platform or its analytical engine',
      'Use automated systems (bots, scrapers) to access the Platform without our written permission',
      'Upload data that you do not have the legal right to share or process',
      'Resell, sublicense, or redistribute access to the Platform or its outputs without our written consent',
    ],
  },
  {
    title: '5. Data Ownership',
    body: null,
    subsections: [
      {
        subtitle: '5.1 Your Data',
        text: 'You retain full ownership of all commercial portfolio data you enter into or upload to the Platform. We do not claim any ownership rights over your data. You grant us a limited, non-exclusive licence to process your data solely for the purpose of delivering the Platform\u2019s analytical services to you.',
      },
      {
        subtitle: '5.2 Platform IP',
        text: 'The MarginCOS platform, including its analytical engine, algorithms, user interface, design, documentation, and all associated intellectual property, remains the exclusive property of Carthena Advisory. These Terms do not grant you any rights to our intellectual property beyond the limited right to use the Platform as described herein.',
      },
      {
        subtitle: '5.3 Analytical Outputs',
        text: 'Reports, analyses, and recommendations generated by the Platform based on your data are provided for your internal business use. You may share these outputs within your organisation but may not resell or publicly distribute them.',
      },
    ],
  },
  {
    title: '6. Subscription and Payment',
    body: null,
    subsections: [
      {
        subtitle: '6.1 Plans',
        text: 'MarginCOS is offered under tiered subscription plans (Essentials, Professional, and Enterprise), each with different features and pricing as described on our pricing page. Enterprise plans require a separate agreement.',
      },
      {
        subtitle: '6.2 Billing',
        text: 'Subscriptions are billed in advance on a monthly or annual basis as selected. All fees are quoted and payable in the currency specified at the time of purchase. Fees are non-refundable except as required by applicable law.',
      },
      {
        subtitle: '6.3 Changes to Pricing',
        text: 'We may adjust pricing with at least 30 days\u2019 written notice. Price changes will take effect at the start of your next billing period following the notice.',
      },
    ],
  },
  {
    title: '7. Availability and Support',
    body: 'We aim to maintain Platform availability of 99.5% uptime, measured monthly, excluding scheduled maintenance windows. Scheduled maintenance will be communicated at least 48 hours in advance via email. We do not guarantee uninterrupted access and shall not be liable for downtime caused by factors outside our reasonable control.',
  },
  {
    title: '8. Limitation of Liability',
    body: null,
    subsections: [
      {
        subtitle: '8.1 No Financial Advice',
        text: 'MarginCOS provides analytical outputs based on the data you provide. These outputs are intended to support your decision-making but do not constitute financial, legal, or professional advice. You are solely responsible for all business decisions made based on Platform outputs.',
      },
      {
        subtitle: '8.2 Limitation',
        text: 'To the maximum extent permitted by Nigerian law, Carthena Advisory\u2019s total aggregate liability arising out of or in connection with these Terms or your use of the Platform shall not exceed the total fees paid by you in the twelve (12) months preceding the event giving rise to the claim.',
      },
      {
        subtitle: '8.3 Exclusions',
        text: 'We shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, revenue, data, or business opportunities, even if we have been advised of the possibility of such damages.',
      },
    ],
  },
  {
    title: '9. Termination',
    body: null,
    subsections: [
      {
        subtitle: '9.1 By You',
        text: 'You may cancel your subscription at any time via your account settings or by contacting us. Cancellation takes effect at the end of your current billing period.',
      },
      {
        subtitle: '9.2 By Us',
        text: 'We may suspend or terminate your access immediately if you breach these Terms, fail to pay fees when due, or if continued access poses a security risk. We will provide reasonable notice where practicable.',
      },
      {
        subtitle: '9.3 Effect of Termination',
        text: 'Upon termination, your access to the Platform will cease. Your commercial data will be retained for 90 days following termination to allow for data export, after which it will be permanently deleted. You may request immediate deletion at any time.',
      },
    ],
  },
  {
    title: '10. Indemnification',
    body: 'You agree to indemnify and hold harmless Carthena Advisory, its directors, officers, employees, and agents from any claims, damages, losses, or expenses (including reasonable legal fees) arising out of your breach of these Terms, your misuse of the Platform, or your violation of any applicable law or third-party rights.',
  },
  {
    title: '11. Modifications to Terms',
    body: 'We may modify these Terms from time to time. Material changes will be communicated via email to registered users at least 30 days before they take effect. Continued use of the Platform after the effective date of changes constitutes acceptance of the updated Terms. If you do not agree with any changes, you may terminate your account before the changes take effect.',
  },
  {
    title: '12. Governing Law and Dispute Resolution',
    body: 'These Terms are governed by and construed in accordance with the laws of the Federal Republic of Nigeria. Any dispute arising out of or in connection with these Terms shall first be referred to mediation. If mediation fails to resolve the dispute within 30 days, either party may refer the matter to arbitration under the Arbitration and Mediation Act 2023 of Nigeria, with proceedings held in Lagos, Nigeria.',
  },
  {
    title: '13. Severability',
    body: 'If any provision of these Terms is found to be invalid or unenforceable by a court of competent jurisdiction, the remaining provisions shall continue in full force and effect.',
  },
  {
    title: '14. Contact',
    body: null,
    contact: true,
  },
];

export default function TermsPage() {
  return (
    <>
      <Head>
        <title>Terms of Service | MarginCOS</title>
        <meta name="description" content="Terms of Service for MarginCOS — subscription, data ownership, liability, and governing law." />
        <link rel="canonical" href="https://margincos.com/terms" />
        <meta property="og:title" content="Terms of Service | MarginCOS" />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://margincos.com/terms" />
        <meta property="og:description" content="Terms of Service for MarginCOS — subscription, data ownership, liability, and governing law." />
        <meta name="twitter:card" content="summary" />
        <meta name="twitter:title" content="Terms of Service | MarginCOS" />
        <meta name="twitter:description" content="Terms of Service for MarginCOS — subscription, data ownership, liability, and governing law." />
      </Head>
      <div className="min-h-screen">
        <PublicNav />
        <section className="hero-mesh pt-28 pb-16 md:pt-36 md:pb-20">
          <div className="max-w-4xl mx-auto px-6 text-center">
            <h1 className="text-3xl md:text-5xl font-black text-white leading-tight">Terms of Service</h1>
            <p className="mt-4 text-sm text-white/50">Last updated: {LAST_UPDATED}</p>
          </div>
        </section>

        <section className="bg-white py-20 md:py-28">
          <div className="max-w-3xl mx-auto px-6 space-y-10">
            {sections.map((s, i) => (
              <div key={i}>
                <h2 className="text-lg font-bold text-navy mb-3">{s.title}</h2>
                {s.body && <p className="text-sm text-slate-600 leading-relaxed">{s.body}</p>}
                {s.list && (
                  <ul className="mt-3 space-y-2">
                    {s.list.map((item, j) => (
                      <li key={j} className="flex items-start gap-2 text-sm text-slate-600 leading-relaxed">
                        <span className="text-teal mt-1 flex-shrink-0">&bull;</span>
                        <span>{item}</span>
                      </li>
                    ))}
                  </ul>
                )}
                {s.after && <p className="mt-3 text-sm text-slate-600 leading-relaxed">{s.after}</p>}
                {s.subsections && s.subsections.map((sub, k) => (
                  <div key={k} className="mt-4">
                    <h3 className="text-sm font-semibold text-navy mb-2">{sub.subtitle}</h3>
                    {sub.text && <p className="text-sm text-slate-600 leading-relaxed">{sub.text}</p>}
                    {sub.list && (
                      <ul className="mt-2 space-y-1.5">
                        {sub.list.map((item, j) => (
                          <li key={j} className="flex items-start gap-2 text-sm text-slate-600 leading-relaxed">
                            <span className="text-teal mt-1 flex-shrink-0">&bull;</span>
                            <span>{item}</span>
                          </li>
                        ))}
                      </ul>
                    )}
                  </div>
                ))}
                {s.contact && (
                  <div className="text-sm text-slate-600 leading-relaxed space-y-1">
                    <p>For questions about these Terms, contact us at:</p>
                    <p className="mt-3 font-medium text-navy">Carthena Advisory</p>
                    <p>Email: <a href="mailto:info@carthenaadvisory.com" className="text-teal hover:underline">info@carthenaadvisory.com</a></p>
                    <p>Website: <a href="https://carthenaadvisory.com" target="_blank" rel="noopener noreferrer" className="text-teal hover:underline">carthenaadvisory.com</a></p>
                  </div>
                )}
              </div>
            ))}
          </div>
        </section>

        <PublicFooter />
      </div>
    </>
  );
}
